export const siteUrl = "https://vstretch.blocksdev.pro";
export const repository = "https://github.com/blocksdevpro/vstretch";
export const downloadEndpoint = "/download";
export const downloadUrl = `${siteUrl}/download`;
export const installPsEndpoint = "/install.ps1";
export const installShEndpoint = "/install.sh";
export const changelogEndpoint = "/changelog";
export const installCommand = `irm ${siteUrl}/install.ps1 | iex`;
export const installShCommand = `curl -fsSL ${siteUrl}/install.sh | sh`;
